project:
  type: website
  output-dir: C:\Users\lwill01.stu\OneDrive - UBC\Documents\GitHub\E-Portfolio

website:
  title: "Your E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: lidr_boulders.qmd
        text: LiDAR Boulder Project

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

